"""RAGGuard package."""

from ragguard.local_rag_integration import (
    ApprovedChunk, BoundaryResult, ChunkLifecycle,
    ConfidentialityTransformationRecord, DataFlowStageContract,
    ExternalIOClass, ExternalIOCounters, IntegrationApproval,
    IntegrationDataClass, IntegrationResult, IntegrationReview,
    IntegrationRoleContext, LocalRAGDataFlowPlan, LocalRAGIntegrationError,
    LocalRAGIntegrationManifest, LocalRAGIntegrationReceipt, LoggingClass,
    PersistenceClass, RAGStage, RealDataTrialEligibility, ReviewResult,
    SensitiveClass, StageGateDecision, StageGateState,
    SyntheticConfidentialFixture, TestOnlyVectorStore,
    TrialEligibilityState, evaluate_embedding_boundary,
    evaluate_logging_cache_boundary, evaluate_prompt_boundary,
    evaluate_retrieval_boundary, evaluate_stage_gate,
    evaluate_trial_eligibility, issue_passed_receipt, transform_fixture,
)
from ragguard.local_rag_environment import (
    MAX_ENVIRONMENT_EVIDENCE_AGE, BuildVerificationResult,
    ConfigurationVerificationResult, DependencyVerificationResult,
    EnvironmentApproval, EnvironmentApprovalResult, EnvironmentAttestationDecision,
    EnvironmentAttestationEvidence, EnvironmentAttestationState,
    EnvironmentAttestationSuite, EnvironmentClass as LocalRAGEnvironmentClass,
    EnvironmentCredentialMode, EnvironmentDataClass, EnvironmentNetworkMode,
    EnvironmentReview, EnvironmentReviewResult, EnvironmentRoleContext,
    EnvironmentStorageMode, FixtureSafetyVerificationResult,
    LocalRAGEnvironmentError, LocalRAGEnvironmentManifest,
    LoggingSafetyVerificationResult, NetworkIsolationVerificationResult,
    StorageIsolationVerificationResult, VerificationResult,
    evaluate_environment_attestation, validate_environment_approval,
)
from ragguard.local_rag_execution import (
    ApprovedLocalRAGExecutionSession, ControlledLocalRAGExecutionAdapter,
    ExecutionSideEffectAccounting, LocalRAGExecutionError,
    LocalRAGExecutionSessionApproval, LocalRAGExecutionSessionRequest,
    LocalRAGExecutionSessionReview, RealDataTrialReadinessDecision,
    RealDataTrialReadinessState, SessionApprovalResult, SessionAuthorizationState,
    SessionExecutionApproval, SessionExecutionReceipt, SessionExecutionResult,
    SessionExecutionReview, SessionLifecycle, SessionRegistryFault,
    SessionRegistryReason, SessionRegistryResult, SessionReviewResult,
    SessionRoleContext, StageExecutionEvidence, StageExecutionResult,
    TestOnlySessionRegistry, evaluate_real_data_trial_readiness,
    validate_v022_integration_chain,
)
from ragguard.real_data_trial import (
    RealDataClass, RealDataClassificationPolicy, RealDataTrialError,
    RealDataTrialScope, TrialCacheClass, TrialCachePolicy,
    TrialExportClass, TrialExportPolicy, TrialLoggingClass,
    TrialLoggingPolicy, TrialPersistenceClass, TrialPersistencePolicy,
    TrialRetentionClass, TrialRetentionPolicy, TrialStagePolicy,
    validate_trial_scope_policies,
)
from ragguard.real_data_trial_approval import (
    MAX_TRIAL_READINESS_AGE, ApprovedRealDataTrialRecord, ApprovedTrialState,
    RealDataAccessAuthorizationReadinessDecision,
    RealDataAccessAuthorizationReadinessState, RealDataTrialApprovalError,
    TestOnlyRealDataTrialRegistry, TrialApproval, TrialApprovalRequest,
    TrialApprovalResult, TrialDataGovernanceReview, TrialLifecycle,
    TrialRegistryFault, TrialRegistryReason, TrialRegistryResult,
    TrialReviewResult, TrialRoleContext, TrialSecurityReview,
    TrialSideEffectAccounting, evaluate_real_data_access_authorization_readiness,
    validate_v023_trial_source_chain,
)
from ragguard.real_data_access import (
    RealDataAccessCacheClass, RealDataAccessError, RealDataAccessExportClass,
    RealDataAccessLoggingClass, RealDataAccessNetworkClass,
    RealDataAccessPersistenceClass, RealDataAccessPolicy,
    RealDataAccessRetentionClass, RealDataAccessSelector,
    RealDataAccessSourceClass, RealDataByteClass, RealDataDocumentClass,
    validate_real_data_access_selector_policy,
)
from ragguard.real_data_access_authorization import (
    MAX_ACCESS_REQUEST_AGE, AuthorizationUsageCounterContract,
    RealDataAccessApproval, RealDataAccessApprovalResult,
    RealDataAccessAuthorizationError, RealDataAccessAuthorizationLifecycle,
    RealDataAccessAuthorizationRecord, RealDataAccessAuthorizationState,
    RealDataAccessGovernanceReview, RealDataAccessRegistryFault,
    RealDataAccessRegistryReason, RealDataAccessRegistryResult,
    RealDataAccessRequest, RealDataAccessReviewResult, RealDataAccessRoleContext,
    RealDataAccessSecurityReview, RealDataAccessSideEffectAccounting,
    RealDataOperatorAssignment, RealDataReadExecutionReadinessDecision,
    RealDataReadExecutionReadinessState,
    TestOnlyRealDataAccessAuthorizationRegistry,
    evaluate_real_data_read_execution_readiness, validate_v024_access_source_chain,
)
from ragguard.real_data_read_execution import (
    ControlledReadAdapter, ControlledReadFailure,
    ExplicitRealDataTrialExecutionHook, ExplicitRealDataTrialExecutionState,
    PreReadVerificationResult, PreReadVerificationState,
    ReadExecutionLedgerFault, ReadExecutionLedgerReason,
    ReadExecutionLifecycle, ReadTargetDescriptor,
    RealDataReadAuthorizationContext, RealDataReadExecutionError,
    RealDataReadExecutionRequest, RealDataReadLedgerResult,
    RealDataReadSideEffectAccounting, TestOnlyRealDataReadExecutionLedger,
)
from ragguard.real_data_read_receipt import (
    PostReadClassificationResult, PostReadMaskingVerification,
    PostReadVerificationState, ReadDownstreamState, ReadExecutionResult,
    ReadExecutionResultState, RealDataReadReceipt, RealDataReadReceiptError,
    RealDataReadReceiptResult, VerifiedMaskedContentCandidate,
)
from ragguard.real_target_resolver import (
    ControlledTargetReference, FileIdentitySnapshot, RealTargetResolver,
    RealTargetResolverError, RealTargetResolverPolicy, ResolvedTarget,
    TrialRootClass, TrialRootDescriptor,
)
from ragguard.one_shot_trial import (
    ControlledFilesystemReadAdapter, ControlledFilesystemReadFault,
    IdentityChainEvidence, OneShotTrialError, OneShotTrialExecutionRequest,
    OneShotTrialExecutionResult, OneShotTrialExecutionResultState,
    OneShotTrialLedgerFault, OneShotTrialLedgerResult, OneShotTrialLifecycle,
    OneShotTrialReason, OneShotTrialReceipt, PreOpenVerification,
    PreOpenVerificationResult, TestOnlyOneShotTrialLedger, TrialClosureFault,
    TrialClosureLedgerResult,
)
from ragguard.trial_closure import (
    PostReadEvidence, TrialClosureError, TrialClosureRecord, TrialClosureResult,
)
from ragguard.real_trial_root import (
    LinkReparseVerificationResult,
    NetworkIsolationVerificationResult as RealTrialNetworkIsolationVerificationResult,
    PermissionVerificationResult, RealTrialClosureRequirement,
    RealTrialPurpose, RealTrialPurposeClass, RealTrialRootError,
    RealTrialRootIdentity, RealTrialRootProvisioningRequest,
    RealTrialTargetSelection, RootConfinementVerificationResult,
    RootProvisioningAttestation, RootProvisioningAttestationState,
    RootProvisioningVerificationState, WriteProhibitionVerificationResult,
    fixed_real_trial_closure_policy_digest, fixed_real_trial_policy_summary,
    root_verification_suite_digest, validate_real_trial_root_chain,
)
from ragguard.real_trial_approval import (
    MAX_ONE_SHOT_TRIAL_APPROVAL_AGE, ApprovedOneShotRealDataTrial,
    ApprovedOneShotRealDataTrialLifecycle, ApprovedOneShotRealDataTrialState,
    OneShotTrialApprovalReadinessDecision, OneShotTrialApprovalReadinessState,
    RealTrialApprovalError, RealTrialApprovalRegistryFault,
    RealTrialApprovalRegistryReason, RealTrialApprovalRegistryResult,
    RealTrialApprovalRequest, RealTrialApprovalRoleContext,
    RealTrialApprovalSideEffectAccounting, RealTrialApprovalSourceContext,
    TestOnlyRealTrialApprovalRegistry, TrialAuthorizationReviewResult,
    TrialDataGovernanceReview as OneShotTrialDataGovernanceReview,
    TrialExecutionApproval, TrialExecutionApprovalResult,
    TrialSecurityReview as OneShotTrialSecurityReview,
    evaluate_one_shot_trial_approval_readiness,
    validate_real_trial_approval_source,
)
from ragguard.one_shot_trial_preparation import (
    ExecutionPreparationDecision, ExecutionPreparationReason,
    ExecutionPreparationRequest, ExecutionPreparationSafeSummary,
    ExecutionPreparationSideEffectAccounting, ExecutionPreparationState,
    OneShotTrialExecutionPacket, OneShotTrialPreparationError,
    TestOnlyExecutionPreparationRegistry, prepare_one_shot_trial,
)

from ragguard.equivalence_attestation import (
    EquivalenceApproval,
    EquivalenceApprovalResult,
    EquivalenceAttestationChain,
    EquivalenceCommitReason,
    EquivalenceCommitResult,
    EquivalenceReplaySnapshot,
    EquivalenceReview,
    EquivalenceReviewResult,
    TestEquivalenceAttestationStore,
)
from ragguard.production_equivalence import (
    CANONICAL_PRODUCTION_EQUIVALENCE_DIGEST_ALGORITHM,
    ConfigurationEquivalence,
    EnvironmentEquivalenceContract,
    EquivalenceAssessment,
    EquivalenceAssessmentReason,
    EquivalenceAssessmentResult,
    EquivalenceCriteria,
    EquivalenceEvidenceDescriptor,
    EquivalenceEvidenceSourceKind,
    ProductBehaviorEquivalence,
    ProductionEquivalenceAssessmentRequest,
    ProductionEquivalenceError,
    ProductionEquivalentState,
    canonical_case_coverage_digest,
    evaluate_production_equivalence,
)

from ragguard.manual_validation_execution import (
    CANONICAL_MANUAL_VALIDATION_EXECUTION_DIGEST_ALGORITHM,
    EvidenceCompleteness,
    ManualApprovalResult,
    ManualEvidenceKind,
    ManualExecutionResult,
    ManualReviewResult,
    ManualValidationApproval,
    ManualValidationChain,
    ManualValidationChainCommitResult,
    ManualValidationExecutionError,
    ManualValidationExecutionErrorCategory,
    ManualValidationExecutionEvidence,
    ManualValidationExecutionOutcome,
    ManualValidationExecutionRecord,
    ManualValidationExecutionRequest,
    ManualValidationReview,
    TestManualValidationChainStore,
    TestManualValidationExecutionHarness,
    ValidationEnvironmentContract,
    ValidationFixtureKind,
    ValidationFixtureManifest,
)

from ragguard.authorization_activation import (
    CANONICAL_AUTHORIZATION_ACTIVATION_DIGEST_ALGORITHM,
    ActivationCommitPlan,
    ActivationEvaluation,
    ActivationEvaluationResult,
    ActivationEvaluationSafeSummary,
    ActivationReason,
    ActivationRequest,
    AuthorizationActivationError,
    InMemoryActivationReplayStore,
    evaluate_activation_request,
)
from ragguard.runtime_authorization import (
    CANONICAL_RUNTIME_AUTHORIZATION_DIGEST_ALGORITHM,
    RuntimeApprovalResult,
    RuntimeAuthorizationApproval,
    RuntimeAuthorizationDecision,
    RuntimeAuthorizationError,
    RuntimeAuthorizationReason,
    RuntimeAuthorizationRequest,
    RuntimeAuthorizationResult,
    RuntimeAuthorizationReview,
    RuntimeAuthorizationSafeSummary,
    RuntimeReviewResult,
    evaluate_runtime_authorization,
)
from ragguard.activation_commit import (
    ActivationAuthorizationState,
    AuthorizationCommitFault,
    AuthorizationCommitReason,
    AuthorizationCommitResult,
    RuntimeAuthorizationCommitRecord,
    TestRuntimeAuthorizationLedger,
)
from ragguard.real_persistence import (
    CANONICAL_REAL_PERSISTENCE_DIGEST_ALGORITHM,
    DurableCommitFault,
    DurableCommitResult,
    DurablePersistenceDecision,
    DurablePersistenceReason,
    DurablePersistenceState,
    DurableStoreSnapshot,
    EMPTY_DURABLE_STORE_STATE_DIGEST,
    PersistenceAuthorizationApproval,
    PersistenceAuthorizationRequest,
    PersistenceAuthorizationResult,
    PersistenceAuthorizationReview,
    PersistenceAuthorizationSafeSummary,
    PersistenceCommitReceiptV2,
    PersistenceIntent,
    PersistenceIntentSafeSummary,
    PersistenceTransactionPlan,
    RealPersistenceError,
    TargetStoreClass,
    TestAtomicDurableStore,
    canonical_after_state_digest,
    evaluate_durable_persistence,
)
from ragguard.persistence_recovery import (
    PersistenceRecoveryDecision,
    PersistenceRecoveryReason,
    PersistenceRecoveryRecord,
    PersistenceRecoveryRequest,
    PersistenceRecoveryState,
    evaluate_persistence_recovery,
)
from ragguard.real_world_validation import (
    CANONICAL_REAL_WORLD_VALIDATION_DIGEST_ALGORITHM,
    AuthorizationReviewResult, ControlledEnvironmentManifest,
    ControlledExecutionOutcome, ControlledExecutionResult, CredentialClass,
    DataClass, EnvironmentClass, ExecutionResult, RealWorldExecutionReceipt,
    RealWorldExecutionRequest, RealWorldValidationAuthorizationApproval,
    RealWorldValidationAuthorizationRequest, RealWorldValidationAuthorizationReview,
    RealWorldValidationDecision, RealWorldValidationError, RealWorldValidationPlan,
    SafeScenarioManifest, StorageMode, TestControlledRealWorldExecutionAdapter,
    ValidationDecisionState, ValidationReason, evaluate_real_world_validation,
)
from ragguard.real_world_evidence import (
    EvidenceApprovalResult, EvidenceClass, EvidenceReviewResult,
    ExecutionEvidenceDescriptor, RealWorldEvidenceApproval, RealWorldEvidenceError,
    RealWorldEvidenceReview, RealWorldValidationRecord, TestRealWorldValidationLedger,
    ValidationCommitFault, ValidationCommitReason, ValidationLedgerResult,
    ValidationRecordState,
)
from ragguard.storage_adapter import (
    CANONICAL_STORAGE_ADAPTER_DIGEST_ALGORITHM,
    AdapterClass, AdapterDataClass, AtomicityModel, CredentialMode,
    DurabilityModel, FilesystemMode, IdempotencyModel, IsolationModel,
    NetworkMode, RecoveryModel, StorageAdapterCapability, StorageAdapterError,
    StorageAdapterManifest, StorageAdapterPolicy, StorageAdapterSafeSummary,
    TransactionModel,
)
from ragguard.storage_adapter_attestation import (
    MAX_ADAPTER_EVIDENCE_AGE,
    AdapterApprovalResult, AdapterCapabilityName, AdapterCapabilityTestResult,
    AdapterConformanceReason, AdapterConformanceResult,
    AdapterConformanceState, AdapterEvidenceClass, AdapterLifecycleStatus,
    AdapterRecordState, AdapterRegistryFault, AdapterRegistryReason,
    AdapterRegistryResult, AdapterReviewResult, AdapterRoleContext,
    ApprovedStorageAdapterRecord, StorageAdapterApproval,
    StorageAdapterAttestationEvidence, StorageAdapterReview,
    StorageAdapterCapabilityConformanceResult,
    StorageAdapterConformanceSuiteResult,
    TestApprovedStorageAdapterRegistry, WriteCompatibilityDecision,
    WriteCompatibilityReason, WriteCompatibilityState,
    evaluate_adapter_conformance, evaluate_write_compatibility,
)

from ragguard.production_authorization import (
    CANONICAL_PRODUCTION_AUTHORIZATION_DIGEST_ALGORITHM,
    ProductionAuthorizationCandidate,
    ProductionAuthorizationError,
    ProductionAuthorizationReason,
    ProductionAuthorizationRequest,
    ProductionAuthorizationResult,
    evaluate_production_authorization,
)
from ragguard.production_boundary import (
    CANONICAL_PRODUCTION_BOUNDARY_DIGEST_ALGORITHM,
    CompatibilityEvidenceKind,
    ManualValidationState,
    PersistenceBoundaryMetadata,
    PersistenceState,
    ProductionBoundaryError,
    ProductionBoundaryErrorCategory,
    ProductionBoundaryEvidence,
    RollbackSemantics,
    RuntimeAuthorizationState,
    SecurityReviewState,
    canonical_registry_state_digest,
)
from ragguard.production_persistence import (
    CANONICAL_PRODUCTION_PERSISTENCE_DIGEST_ALGORITHM,
    DurabilityMode,
    InMemoryPersistenceStore,
    PersistedAuthorizationRecord,
    PersistedAuthorizationSafeSummary,
    PersistenceCommitReceipt,
    PersistenceCommitFault,
    PersistenceCommitRequest,
    PersistenceCommitResult,
    PersistencePolicy,
    PersistenceReason,
    PersistenceRetentionPolicy,
    PersistenceRollbackPolicy,
    PersistenceStoreSnapshot,
    ProductionPersistenceError,
    create_persisted_authorization_record,
)

from ragguard.manual_evidence_import import (
    ManualEvidenceImportError,
    ManualEvidenceImportErrorCategory,
    ManualEvidenceImportRequest,
    ManualEvidenceImportResult,
    ManualEvidenceSourceKind,
    import_manual_validation_evidence,
)
from ragguard.production_admission import (
    ProductionAdmissionDecision,
    ProductionAdmissionError,
    ProductionAdmissionErrorCategory,
    ProductionAdmissionReason,
    ProductionAdmissionRequest,
    ReviewerAttestation,
    ReviewerAttestationOutcome,
    RevalidationTrigger,
    canonical_approval_metadata_digest,
    evaluate_production_admission,
)
from ragguard.registry_admission import (
    CANONICAL_REGISTRY_ADMISSION_DIGEST_ALGORITHM,
    RegistryAdmissionEntry,
    RegistryAdmissionEntrySafeSummary,
    RegistryAdmissionError,
    RegistryAdmissionEvent,
    RegistryAdmissionReason,
    RegistryAdmissionRequest,
    RegistryAdmissionRequestSafeSummary,
    RegistryAdmissionResult,
    RegistryAdmissionSafeSummary,
    TestRegistryAdmissionStore,
    enforce_registry_admission,
)
from ragguard.registry_lifecycle import (
    CANONICAL_REGISTRY_LIFECYCLE_DIGEST_ALGORITHM,
    RegistryLifecycleError,
    RegistryLifecycleEvent,
    RegistryLifecycleReason,
    RegistryLifecycleRequest,
    RegistryLifecycleRequestSafeSummary,
    RegistryLifecycleResult,
    RegistryLifecycleSafeSummary,
    TestRegistryLifecycleStore,
    enforce_registry_lifecycle,
)
from ragguard.revalidation import (
    CANONICAL_REVALIDATION_DIGEST_ALGORITHM,
    RevalidationAction,
    RevalidationError,
    RevalidationReason,
    RevalidationRequirement,
    RevalidationRequirementSafeSummary,
    RevalidationTrigger as RegistryRevalidationTrigger,
    RevalidationTriggerKind,
    RevalidationTriggerSafeSummary,
    evaluate_revalidation_requirement,
)
from ragguard.replacement_admission import (
    CANONICAL_REPLACEMENT_ADMISSION_DIGEST_ALGORITHM,
    ReplacementAdmissionDecision,
    ReplacementAdmissionDecisionSafeSummary,
    ReplacementAdmissionError,
    ReplacementAdmissionEvent,
    ReplacementAdmissionReason,
    ReplacementAdmissionRequest,
    ReplacementAdmissionRequestSafeSummary,
    ReplacementAdmissionResult,
    ReplacementAdmissionResultSafeSummary,
    ReplacementCommitFault,
    ReplacementDecisionStatus,
    ReplacementReason,
    ReplacementRegistryEntry,
    ReplacementRegistryEntrySafeSummary,
    TestReplacementAdmissionStore,
    enforce_replacement_admission,
    evaluate_replacement_admission,
)

__version__ = "0.1.0"

__all__ = [
    "ApprovedChunk", "BoundaryResult", "ChunkLifecycle",
    "ConfidentialityTransformationRecord", "DataFlowStageContract",
    "ExternalIOClass", "ExternalIOCounters", "IntegrationApproval",
    "IntegrationDataClass", "IntegrationResult", "IntegrationReview",
    "IntegrationRoleContext", "LocalRAGDataFlowPlan", "LocalRAGIntegrationError",
    "LocalRAGIntegrationManifest", "LocalRAGIntegrationReceipt", "LoggingClass",
    "PersistenceClass", "RAGStage", "RealDataTrialEligibility", "ReviewResult",
    "SensitiveClass", "StageGateDecision", "StageGateState",
    "SyntheticConfidentialFixture", "TestOnlyVectorStore",
    "TrialEligibilityState", "evaluate_embedding_boundary",
    "evaluate_logging_cache_boundary", "evaluate_prompt_boundary",
    "evaluate_retrieval_boundary", "evaluate_stage_gate",
    "evaluate_trial_eligibility", "issue_passed_receipt", "transform_fixture",
    "MAX_ENVIRONMENT_EVIDENCE_AGE", "BuildVerificationResult",
    "ConfigurationVerificationResult", "DependencyVerificationResult",
    "EnvironmentApproval", "EnvironmentApprovalResult", "EnvironmentAttestationDecision",
    "EnvironmentAttestationEvidence", "EnvironmentAttestationState",
    "EnvironmentAttestationSuite", "LocalRAGEnvironmentClass",
    "EnvironmentCredentialMode", "EnvironmentDataClass", "EnvironmentNetworkMode",
    "EnvironmentReview", "EnvironmentReviewResult", "EnvironmentRoleContext",
    "EnvironmentStorageMode", "FixtureSafetyVerificationResult",
    "LocalRAGEnvironmentError", "LocalRAGEnvironmentManifest",
    "LoggingSafetyVerificationResult", "NetworkIsolationVerificationResult",
    "StorageIsolationVerificationResult", "VerificationResult",
    "evaluate_environment_attestation", "validate_environment_approval",
    "ApprovedLocalRAGExecutionSession", "ControlledLocalRAGExecutionAdapter",
    "ExecutionSideEffectAccounting", "LocalRAGExecutionError",
    "LocalRAGExecutionSessionApproval", "LocalRAGExecutionSessionRequest",
    "LocalRAGExecutionSessionReview", "RealDataTrialReadinessDecision",
    "RealDataTrialReadinessState", "SessionApprovalResult", "SessionAuthorizationState",
    "SessionExecutionApproval", "SessionExecutionReceipt", "SessionExecutionResult",
    "SessionExecutionReview", "SessionLifecycle", "SessionRegistryFault",
    "SessionRegistryReason", "SessionRegistryResult", "SessionReviewResult",
    "SessionRoleContext", "StageExecutionEvidence", "StageExecutionResult",
    "TestOnlySessionRegistry", "evaluate_real_data_trial_readiness",
    "validate_v022_integration_chain",
    "RealDataClass", "RealDataClassificationPolicy", "RealDataTrialError",
    "RealDataTrialScope", "TrialCacheClass", "TrialCachePolicy",
    "TrialExportClass", "TrialExportPolicy", "TrialLoggingClass",
    "TrialLoggingPolicy", "TrialPersistenceClass", "TrialPersistencePolicy",
    "TrialRetentionClass", "TrialRetentionPolicy", "TrialStagePolicy",
    "validate_trial_scope_policies",
    "MAX_TRIAL_READINESS_AGE", "ApprovedRealDataTrialRecord", "ApprovedTrialState",
    "RealDataAccessAuthorizationReadinessDecision",
    "RealDataAccessAuthorizationReadinessState", "RealDataTrialApprovalError",
    "TestOnlyRealDataTrialRegistry", "TrialApproval", "TrialApprovalRequest",
    "TrialApprovalResult", "TrialDataGovernanceReview", "TrialLifecycle",
    "TrialRegistryFault", "TrialRegistryReason", "TrialRegistryResult",
    "TrialReviewResult", "TrialRoleContext", "TrialSecurityReview",
    "TrialSideEffectAccounting", "evaluate_real_data_access_authorization_readiness",
    "validate_v023_trial_source_chain",
    "RealDataAccessCacheClass", "RealDataAccessError",
    "RealDataAccessExportClass", "RealDataAccessLoggingClass",
    "RealDataAccessNetworkClass", "RealDataAccessPersistenceClass",
    "RealDataAccessPolicy", "RealDataAccessRetentionClass",
    "RealDataAccessSelector", "RealDataAccessSourceClass", "RealDataByteClass",
    "RealDataDocumentClass", "validate_real_data_access_selector_policy",
    "MAX_ACCESS_REQUEST_AGE", "AuthorizationUsageCounterContract",
    "RealDataAccessApproval", "RealDataAccessApprovalResult",
    "RealDataAccessAuthorizationError", "RealDataAccessAuthorizationLifecycle",
    "RealDataAccessAuthorizationRecord", "RealDataAccessAuthorizationState",
    "RealDataAccessGovernanceReview", "RealDataAccessRegistryFault",
    "RealDataAccessRegistryReason", "RealDataAccessRegistryResult",
    "RealDataAccessRequest", "RealDataAccessReviewResult",
    "RealDataAccessRoleContext", "RealDataAccessSecurityReview",
    "RealDataAccessSideEffectAccounting", "RealDataOperatorAssignment",
    "RealDataReadExecutionReadinessDecision", "RealDataReadExecutionReadinessState",
    "TestOnlyRealDataAccessAuthorizationRegistry",
    "evaluate_real_data_read_execution_readiness", "validate_v024_access_source_chain",
    "ControlledReadAdapter", "ControlledReadFailure",
    "ExplicitRealDataTrialExecutionHook", "ExplicitRealDataTrialExecutionState",
    "PreReadVerificationResult", "PreReadVerificationState",
    "ReadExecutionLedgerFault", "ReadExecutionLedgerReason",
    "ReadExecutionLifecycle", "ReadTargetDescriptor",
    "RealDataReadAuthorizationContext", "RealDataReadExecutionError",
    "RealDataReadExecutionRequest", "RealDataReadLedgerResult",
    "RealDataReadSideEffectAccounting", "TestOnlyRealDataReadExecutionLedger",
    "PostReadClassificationResult", "PostReadMaskingVerification",
    "PostReadVerificationState", "ReadDownstreamState", "ReadExecutionResult",
    "ReadExecutionResultState", "RealDataReadReceipt", "RealDataReadReceiptError",
    "RealDataReadReceiptResult", "VerifiedMaskedContentCandidate",
    "ControlledTargetReference", "FileIdentitySnapshot", "RealTargetResolver",
    "RealTargetResolverError", "RealTargetResolverPolicy", "ResolvedTarget",
    "TrialRootClass", "TrialRootDescriptor",
    "ControlledFilesystemReadAdapter", "ControlledFilesystemReadFault",
    "IdentityChainEvidence", "OneShotTrialError", "OneShotTrialExecutionRequest",
    "OneShotTrialExecutionResult", "OneShotTrialExecutionResultState",
    "OneShotTrialLedgerFault", "OneShotTrialLedgerResult", "OneShotTrialLifecycle",
    "OneShotTrialReason", "OneShotTrialReceipt", "PreOpenVerification",
    "PreOpenVerificationResult", "TestOnlyOneShotTrialLedger", "TrialClosureFault",
    "TrialClosureLedgerResult", "PostReadEvidence", "TrialClosureError",
    "TrialClosureRecord", "TrialClosureResult",
    "LinkReparseVerificationResult",
    "RealTrialNetworkIsolationVerificationResult",
    "PermissionVerificationResult", "RealTrialClosureRequirement",
    "RealTrialPurpose", "RealTrialPurposeClass", "RealTrialRootError",
    "RealTrialRootIdentity", "RealTrialRootProvisioningRequest",
    "RealTrialTargetSelection", "RootConfinementVerificationResult",
    "RootProvisioningAttestation", "RootProvisioningAttestationState",
    "RootProvisioningVerificationState", "WriteProhibitionVerificationResult",
    "fixed_real_trial_closure_policy_digest", "fixed_real_trial_policy_summary",
    "root_verification_suite_digest", "validate_real_trial_root_chain",
    "MAX_ONE_SHOT_TRIAL_APPROVAL_AGE", "ApprovedOneShotRealDataTrial",
    "ApprovedOneShotRealDataTrialLifecycle", "ApprovedOneShotRealDataTrialState",
    "OneShotTrialApprovalReadinessDecision", "OneShotTrialApprovalReadinessState",
    "RealTrialApprovalError", "RealTrialApprovalRegistryFault",
    "RealTrialApprovalRegistryReason", "RealTrialApprovalRegistryResult",
    "RealTrialApprovalRequest", "RealTrialApprovalRoleContext",
    "RealTrialApprovalSideEffectAccounting", "RealTrialApprovalSourceContext",
    "TestOnlyRealTrialApprovalRegistry", "TrialAuthorizationReviewResult",
    "OneShotTrialDataGovernanceReview", "TrialExecutionApproval",
    "TrialExecutionApprovalResult", "OneShotTrialSecurityReview",
    "evaluate_one_shot_trial_approval_readiness",
    "validate_real_trial_approval_source",
    "ExecutionPreparationDecision", "ExecutionPreparationReason",
    "ExecutionPreparationRequest", "ExecutionPreparationSafeSummary",
    "ExecutionPreparationSideEffectAccounting", "ExecutionPreparationState",
    "OneShotTrialExecutionPacket", "OneShotTrialPreparationError",
    "TestOnlyExecutionPreparationRegistry", "prepare_one_shot_trial",
    "CANONICAL_STORAGE_ADAPTER_DIGEST_ALGORITHM",
    "MAX_ADAPTER_EVIDENCE_AGE",
    "AdapterApprovalResult", "AdapterCapabilityName", "AdapterCapabilityTestResult",
    "AdapterClass", "AdapterConformanceReason",
    "AdapterConformanceResult", "AdapterConformanceState", "AdapterDataClass",
    "AdapterEvidenceClass", "AdapterLifecycleStatus", "AdapterRecordState",
    "AdapterRegistryFault", "AdapterRegistryReason", "AdapterRegistryResult",
    "AdapterReviewResult", "AdapterRoleContext", "ApprovedStorageAdapterRecord",
    "AtomicityModel", "CredentialMode", "DurabilityModel", "FilesystemMode",
    "IdempotencyModel", "IsolationModel", "NetworkMode", "RecoveryModel",
    "StorageAdapterApproval", "StorageAdapterAttestationEvidence",
    "StorageAdapterCapabilityConformanceResult",
    "StorageAdapterCapability", "StorageAdapterError", "StorageAdapterManifest",
    "StorageAdapterConformanceSuiteResult", "StorageAdapterPolicy",
    "StorageAdapterReview", "StorageAdapterSafeSummary",
    "TestApprovedStorageAdapterRegistry", "TransactionModel",
    "WriteCompatibilityDecision", "WriteCompatibilityReason",
    "WriteCompatibilityState", "evaluate_adapter_conformance",
    "evaluate_write_compatibility",
    "CANONICAL_REAL_PERSISTENCE_DIGEST_ALGORITHM",
    "DurableCommitFault",
    "DurableCommitResult",
    "DurablePersistenceDecision",
    "DurablePersistenceReason",
    "DurablePersistenceState",
    "DurableStoreSnapshot",
    "EMPTY_DURABLE_STORE_STATE_DIGEST",
    "PersistenceAuthorizationApproval",
    "PersistenceAuthorizationRequest",
    "PersistenceAuthorizationResult",
    "PersistenceAuthorizationReview",
    "PersistenceAuthorizationSafeSummary",
    "PersistenceCommitReceiptV2",
    "PersistenceIntent",
    "PersistenceIntentSafeSummary",
    "PersistenceRecoveryDecision",
    "PersistenceRecoveryReason",
    "PersistenceRecoveryRecord",
    "PersistenceRecoveryRequest",
    "PersistenceRecoveryState",
    "PersistenceTransactionPlan",
    "RealPersistenceError",
    "TargetStoreClass",
    "TestAtomicDurableStore",
    "canonical_after_state_digest",
    "evaluate_durable_persistence",
    "evaluate_persistence_recovery",
    "CANONICAL_RUNTIME_AUTHORIZATION_DIGEST_ALGORITHM",
    "ActivationAuthorizationState",
    "AuthorizationCommitFault",
    "AuthorizationCommitReason",
    "AuthorizationCommitResult",
    "RuntimeApprovalResult",
    "RuntimeAuthorizationApproval",
    "RuntimeAuthorizationCommitRecord",
    "RuntimeAuthorizationDecision",
    "RuntimeAuthorizationError",
    "RuntimeAuthorizationReason",
    "RuntimeAuthorizationRequest",
    "RuntimeAuthorizationResult",
    "RuntimeAuthorizationReview",
    "RuntimeAuthorizationSafeSummary",
    "RuntimeReviewResult",
    "TestRuntimeAuthorizationLedger",
    "evaluate_runtime_authorization",
    "CANONICAL_AUTHORIZATION_ACTIVATION_DIGEST_ALGORITHM",
    "CANONICAL_MANUAL_VALIDATION_EXECUTION_DIGEST_ALGORITHM",
    "CANONICAL_PRODUCTION_AUTHORIZATION_DIGEST_ALGORITHM",
    "CANONICAL_PRODUCTION_BOUNDARY_DIGEST_ALGORITHM",
    "CANONICAL_PRODUCTION_EQUIVALENCE_DIGEST_ALGORITHM",
    "CANONICAL_PRODUCTION_PERSISTENCE_DIGEST_ALGORITHM",
    "CANONICAL_REGISTRY_ADMISSION_DIGEST_ALGORITHM",
    "CANONICAL_REGISTRY_LIFECYCLE_DIGEST_ALGORITHM",
    "CANONICAL_REVALIDATION_DIGEST_ALGORITHM",
    "CANONICAL_REPLACEMENT_ADMISSION_DIGEST_ALGORITHM",
    "ActivationCommitPlan",
    "ActivationEvaluation",
    "ActivationEvaluationResult",
    "ActivationEvaluationSafeSummary",
    "ActivationReason",
    "ActivationRequest",
    "AuthorizationActivationError",
    "ManualEvidenceImportError",
    "ManualEvidenceImportErrorCategory",
    "ManualEvidenceImportRequest",
    "ManualEvidenceImportResult",
    "ManualEvidenceSourceKind",
    "EvidenceCompleteness",
    "ManualApprovalResult",
    "ManualEvidenceKind",
    "ManualExecutionResult",
    "ManualReviewResult",
    "ManualValidationApproval",
    "ManualValidationChain",
    "ManualValidationChainCommitResult",
    "ManualValidationExecutionError",
    "ManualValidationExecutionErrorCategory",
    "ManualValidationExecutionEvidence",
    "ManualValidationExecutionOutcome",
    "ManualValidationExecutionRecord",
    "ManualValidationExecutionRequest",
    "ManualValidationReview",
    "CompatibilityEvidenceKind",
    "ConfigurationEquivalence",
    "DurabilityMode",
    "EnvironmentEquivalenceContract",
    "EquivalenceApproval",
    "EquivalenceApprovalResult",
    "EquivalenceAssessment",
    "EquivalenceAssessmentReason",
    "EquivalenceAssessmentResult",
    "EquivalenceAttestationChain",
    "EquivalenceCommitReason",
    "EquivalenceCommitResult",
    "EquivalenceCriteria",
    "EquivalenceEvidenceDescriptor",
    "EquivalenceEvidenceSourceKind",
    "EquivalenceReplaySnapshot",
    "EquivalenceReview",
    "EquivalenceReviewResult",
    "InMemoryActivationReplayStore",
    "InMemoryPersistenceStore",
    "ManualValidationState",
    "PersistenceBoundaryMetadata",
    "PersistedAuthorizationRecord",
    "PersistedAuthorizationSafeSummary",
    "PersistenceCommitReceipt",
    "PersistenceCommitFault",
    "PersistenceCommitRequest",
    "PersistenceCommitResult",
    "PersistencePolicy",
    "PersistenceReason",
    "PersistenceRetentionPolicy",
    "PersistenceRollbackPolicy",
    "PersistenceStoreSnapshot",
    "PersistenceState",
    "ProductionAuthorizationCandidate",
    "ProductionAuthorizationError",
    "ProductionAuthorizationReason",
    "ProductionAuthorizationRequest",
    "ProductionAuthorizationResult",
    "ProductionBoundaryError",
    "ProductionBoundaryErrorCategory",
    "ProductionBoundaryEvidence",
    "ProductionEquivalenceAssessmentRequest",
    "ProductionEquivalenceError",
    "ProductionEquivalentState",
    "ProductBehaviorEquivalence",
    "ProductionPersistenceError",
    "RollbackSemantics",
    "RuntimeAuthorizationState",
    "SecurityReviewState",
    "ProductionAdmissionDecision",
    "ProductionAdmissionError",
    "ProductionAdmissionErrorCategory",
    "ProductionAdmissionReason",
    "ProductionAdmissionRequest",
    "RegistryAdmissionEntry",
    "RegistryAdmissionEntrySafeSummary",
    "RegistryAdmissionError",
    "RegistryAdmissionEvent",
    "RegistryAdmissionReason",
    "RegistryAdmissionRequest",
    "RegistryAdmissionRequestSafeSummary",
    "RegistryAdmissionResult",
    "RegistryAdmissionSafeSummary",
    "RegistryLifecycleError",
    "RegistryLifecycleEvent",
    "RegistryLifecycleReason",
    "RegistryLifecycleRequest",
    "RegistryLifecycleRequestSafeSummary",
    "RegistryLifecycleResult",
    "RegistryLifecycleSafeSummary",
    "RegistryRevalidationTrigger",
    "ReplacementAdmissionDecision",
    "ReplacementAdmissionDecisionSafeSummary",
    "ReplacementAdmissionError",
    "ReplacementAdmissionEvent",
    "ReplacementAdmissionReason",
    "ReplacementAdmissionRequest",
    "ReplacementAdmissionRequestSafeSummary",
    "ReplacementAdmissionResult",
    "ReplacementAdmissionResultSafeSummary",
    "ReplacementCommitFault",
    "ReplacementDecisionStatus",
    "ReplacementReason",
    "ReplacementRegistryEntry",
    "ReplacementRegistryEntrySafeSummary",
    "ReviewerAttestation",
    "ReviewerAttestationOutcome",
    "RevalidationTrigger",
    "RevalidationAction",
    "RevalidationError",
    "RevalidationReason",
    "RevalidationRequirement",
    "RevalidationRequirementSafeSummary",
    "RevalidationTriggerKind",
    "RevalidationTriggerSafeSummary",
    "TestRegistryAdmissionStore",
    "TestEquivalenceAttestationStore",
    "TestManualValidationChainStore",
    "TestManualValidationExecutionHarness",
    "TestRegistryLifecycleStore",
    "TestReplacementAdmissionStore",
    "enforce_registry_admission",
    "enforce_registry_lifecycle",
    "evaluate_production_admission",
    "evaluate_replacement_admission",
    "evaluate_revalidation_requirement",
    "import_manual_validation_evidence",
    "enforce_replacement_admission",
    "evaluate_activation_request",
    "evaluate_production_authorization",
    "create_persisted_authorization_record",
    "canonical_registry_state_digest",
    "canonical_approval_metadata_digest",
    "canonical_case_coverage_digest",
    "evaluate_production_equivalence",
    "ValidationEnvironmentContract",
    "ValidationFixtureKind",
    "ValidationFixtureManifest",
    "CANONICAL_REAL_WORLD_VALIDATION_DIGEST_ALGORITHM",
    "AuthorizationReviewResult", "ControlledEnvironmentManifest",
    "ControlledExecutionOutcome", "ControlledExecutionResult", "CredentialClass",
    "DataClass", "EnvironmentClass", "ExecutionResult", "RealWorldExecutionReceipt",
    "RealWorldExecutionRequest", "RealWorldValidationAuthorizationApproval",
    "RealWorldValidationAuthorizationRequest", "RealWorldValidationAuthorizationReview",
    "RealWorldValidationDecision", "RealWorldValidationError", "RealWorldValidationPlan",
    "SafeScenarioManifest", "StorageMode", "TestControlledRealWorldExecutionAdapter",
    "ValidationDecisionState", "ValidationReason", "evaluate_real_world_validation",
    "EvidenceApprovalResult", "EvidenceClass", "EvidenceReviewResult",
    "ExecutionEvidenceDescriptor", "RealWorldEvidenceApproval", "RealWorldEvidenceError",
    "RealWorldEvidenceReview", "RealWorldValidationRecord", "TestRealWorldValidationLedger",
    "ValidationCommitFault", "ValidationCommitReason", "ValidationLedgerResult",
    "ValidationRecordState",
]
