"""RAGGuard package."""

from ragguard.manual_evidence_import import (
    ManualEvidenceImportError,
    ManualEvidenceImportErrorCategory,
    ManualEvidenceImportRequest,
    ManualEvidenceImportResult,
    ManualEvidenceSourceKind,
    import_manual_validation_evidence,
)
from ragguard.production_admission import (
    ProductionAdmissionDecision,
    ProductionAdmissionError,
    ProductionAdmissionErrorCategory,
    ProductionAdmissionReason,
    ProductionAdmissionRequest,
    ReviewerAttestation,
    ReviewerAttestationOutcome,
    RevalidationTrigger,
    evaluate_production_admission,
)
from ragguard.registry_admission import (
    CANONICAL_REGISTRY_ADMISSION_DIGEST_ALGORITHM,
    RegistryAdmissionEntry,
    RegistryAdmissionEntrySafeSummary,
    RegistryAdmissionError,
    RegistryAdmissionEvent,
    RegistryAdmissionReason,
    RegistryAdmissionRequest,
    RegistryAdmissionRequestSafeSummary,
    RegistryAdmissionResult,
    RegistryAdmissionSafeSummary,
    TestRegistryAdmissionStore,
    enforce_registry_admission,
)
from ragguard.registry_lifecycle import (
    CANONICAL_REGISTRY_LIFECYCLE_DIGEST_ALGORITHM,
    RegistryLifecycleError,
    RegistryLifecycleEvent,
    RegistryLifecycleReason,
    RegistryLifecycleRequest,
    RegistryLifecycleRequestSafeSummary,
    RegistryLifecycleResult,
    RegistryLifecycleSafeSummary,
    TestRegistryLifecycleStore,
    enforce_registry_lifecycle,
)
from ragguard.revalidation import (
    CANONICAL_REVALIDATION_DIGEST_ALGORITHM,
    RevalidationAction,
    RevalidationError,
    RevalidationReason,
    RevalidationRequirement,
    RevalidationRequirementSafeSummary,
    RevalidationTrigger as RegistryRevalidationTrigger,
    RevalidationTriggerKind,
    RevalidationTriggerSafeSummary,
    evaluate_revalidation_requirement,
)

__version__ = "0.1.0"

__all__ = [
    "CANONICAL_REGISTRY_ADMISSION_DIGEST_ALGORITHM",
    "CANONICAL_REGISTRY_LIFECYCLE_DIGEST_ALGORITHM",
    "CANONICAL_REVALIDATION_DIGEST_ALGORITHM",
    "ManualEvidenceImportError",
    "ManualEvidenceImportErrorCategory",
    "ManualEvidenceImportRequest",
    "ManualEvidenceImportResult",
    "ManualEvidenceSourceKind",
    "ProductionAdmissionDecision",
    "ProductionAdmissionError",
    "ProductionAdmissionErrorCategory",
    "ProductionAdmissionReason",
    "ProductionAdmissionRequest",
    "RegistryAdmissionEntry",
    "RegistryAdmissionEntrySafeSummary",
    "RegistryAdmissionError",
    "RegistryAdmissionEvent",
    "RegistryAdmissionReason",
    "RegistryAdmissionRequest",
    "RegistryAdmissionRequestSafeSummary",
    "RegistryAdmissionResult",
    "RegistryAdmissionSafeSummary",
    "RegistryLifecycleError",
    "RegistryLifecycleEvent",
    "RegistryLifecycleReason",
    "RegistryLifecycleRequest",
    "RegistryLifecycleRequestSafeSummary",
    "RegistryLifecycleResult",
    "RegistryLifecycleSafeSummary",
    "RegistryRevalidationTrigger",
    "ReviewerAttestation",
    "ReviewerAttestationOutcome",
    "RevalidationTrigger",
    "RevalidationAction",
    "RevalidationError",
    "RevalidationReason",
    "RevalidationRequirement",
    "RevalidationRequirementSafeSummary",
    "RevalidationTriggerKind",
    "RevalidationTriggerSafeSummary",
    "TestRegistryAdmissionStore",
    "TestRegistryLifecycleStore",
    "enforce_registry_admission",
    "enforce_registry_lifecycle",
    "evaluate_production_admission",
    "evaluate_revalidation_requirement",
    "import_manual_validation_evidence",
]
